apiVersion: v1
kind: Namespace
metadata:
  name: cron-test
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: cron-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:2.4  # Replace with your desired HTTPD image
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m   # Define CPU request here
          limits:
            cpu: 500m   # Optionally, define CPU limit here

---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: cron-test
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80   # Port on the service
      targetPort: 80   # Port on the container
      nodePort: 30080  # NodePort (replace with your desired port number)
