kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: httpd
    namespace: http-scaling-test
spec:
    hosts:
        - app1.example.com
    pathPrefixes:
        - /
    scaleTargetRef:
        name: httpd-deployment
        kind: Deployment
        apiVersion: apps/v1
        service: httpd-service
        port: 80
    replicas:
        min: 0
        max: 5
    scaledownPeriod: 300
    scalingMetric:
        requestRate:
            granularity: 1s
            targetValue: 100
            window: 1m
