apiVersion: v1
kind: Namespace
metadata:
  name: cpu-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: cpu-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:2.4
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: cpu-test
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007  # You can specify a nodePort value within the range 30000-32767
