apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: httpd-scaledobject
  namespace: cpu-test
spec:
  scaleTargetRef:
    name: httpd-deployment
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50"
